[package]
name = "ostrich"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.40", features = ["derive"] }
m68000 = "0.2.3"
macfmt = { version = "0.1.0", path = "../macfmt" }
