[package]
name = "mdisk"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
bilge = "0.2.0"
binrw = "0.15.0"
clap = { version = "4.5.40", features = ["derive"] }
comfy-table = "7.1.4"
humansize = "2.1.3"
macfmt = { version = "0.1.0", path = "../macfmt" }
term-table = "1.4.0"
